#!/bin/bash
# ETAP Asset Management System - Complete Startup Guide
# This guide covers running the entire stack from Python/Backend/Frontend

echo "=================================="
echo "ETAP System - Complete Startup"
echo "=================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Step 1: Database Setup
echo -e "${YELLOW}[STEP 1] Database Setup${NC}"
echo "=================================================="
echo ""
echo "PostgreSQL Command:"
echo "  createdb etap_db"
echo ""
echo "Then update: app-back/src/main/resources/application.properties"
echo "  spring.datasource.url=jdbc:postgresql://localhost:5432/etap_db"
echo "  spring.datasource.username=postgres"
echo "  spring.datasource.password=your_password"
echo ""
read -p "Press ENTER when database is ready..."
echo ""

# Step 2: Python Setup
echo -e "${YELLOW}[STEP 2] Python ML Modules Setup${NC}"
echo "=================================================="
echo ""
echo "Run these commands:"
echo ""
echo "  # Install required packages"
echo "  pip install python-docx"
echo ""
echo "  # Navigate to project"
echo "  cd c:\\Users\\amrou\\OneDrive\\Desktop\\PFE\\app"
echo ""
echo "  # Verify Python modules exist:"
echo "  ls -la *.py"
echo ""
echo "Expected files:"
echo "  - ocr_module.py"
echo "  - anomaly_detection_module.py"
echo "  - forecasting_module.py"
echo "  - stock_optimization_module.py"
echo ""
read -p "Press ENTER when Python setup is complete..."
echo ""

# Step 3: Backend Build & Start
echo -e "${YELLOW}[STEP 3] Backend Build & Start${NC}"
echo "=================================================="
echo ""
echo "In Terminal 1, run:"
echo ""
echo "  cd c:\\Users\\amrou\\OneDrive\\Desktop\\PFE\\app\\app-back"
echo "  mvn clean package -DskipTests"
echo "  mvn spring-boot:run"
echo ""
echo "Backend should start at: http://localhost:8080"
echo ""
echo "Check logs for:"
echo "  - 'Started AppBackApplication in X seconds'"
echo "  - 'Hibernate: create table' (25 table creations)"
echo ""
read -p "Press ENTER after backend is running..."
echo ""

# Step 4: Frontend Build & Start
echo -e "${YELLOW}[STEP 4] Frontend Build & Start${NC}"
echo "=================================================="
echo ""
echo "In Terminal 2, run:"
echo ""
echo "  cd c:\\Users\\amrou\\OneDrive\\Desktop\\PFE\\app\\app-front\\consommables"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "Frontend should start at: http://localhost:5173"
echo ""
read -p "Press ENTER after frontend is running..."
echo ""

# Step 5: Access Application
echo -e "${YELLOW}[STEP 5] Access Application${NC}"
echo "=================================================="
echo ""
echo "Open your browser and navigate to:"
echo "  ${GREEN}http://localhost:5173${NC}"
echo ""
echo "Login Credentials:"
echo "  Username: admin"
echo "  Password: password"
echo ""
echo "Then navigate to: ${GREEN}http://localhost:5173/admin/dashboard/overview${NC}"
echo ""
echo ""

# Testing
echo -e "${YELLOW}[STEP 6] Test Backend API${NC}"
echo "=================================================="
echo ""
echo "In Terminal 3 (or use Postman), test the API:"
echo ""
echo "1. Get all suppliers:"
echo "   curl -H 'Authorization: Bearer {TOKEN}' \\"
echo "        http://localhost:8080/api/supply-chain/suppliers"
echo ""
echo "2. Create a supplier:"
echo "   curl -X POST http://localhost:8080/api/supply-chain/suppliers \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -H 'Authorization: Bearer {TOKEN}' \\"
echo "        -d '{\"name\":\"Test Supplier\",\"email\":\"test@example.com\"}'"
echo ""
echo "3. Test Python Integration (Anomaly Detection):"
echo "   curl -X POST http://localhost:8080/api/analytics/anomalies/detect \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -d '{\"history\":[100,102,98,105,103],\"currentValue\":500}'"
echo ""
echo ""

echo -e "${GREEN}=================================="
echo "Startup complete!"
echo "==================================${NC}"
echo ""
echo "System Status:"
echo "  ✓ Backend:  http://localhost:8080"
echo "  ✓ Frontend: http://localhost:5173"
echo "  ✓ Python:   Integrated via Java ProcessBuilder"
echo ""
